import Navbar from "./components/Navbar/Navbar";
import './globals.css'



export const metadata = {
  title: "Duah & Ruqyah",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-col gap-5 p-10 bg-[#F7F8FA] overflow-hidden">
        <Navbar />

        <div>
        {children}
        </div>
      </body>
    </html>
  );
}
